[WIP] [BLUEBUTTON-183] [BLUEBUTTON-184] Updated load testing strategy
TransparentHealth/hhs_ansible pull request #1294
Opened 2018-05-17 17:00 UTC by rnagle

Details to come...

2018-05-18 14:33 UTC, whytheplatypus requested changes

2018-05-18 14:33 UTC, whytheplatypus commented on locust/locustfile.py
>          self.make_req(resource)
at the end of the sequence (which I think is here?) can you make a request to the `revoke-token` endpoint so the load test can kind of clean up after itself?

2018-05-18 14:33 UTC, whytheplatypus commented on locust/locustfile.py
> +        patient = self.get_random_userinfo()
the EOB endpoint shouldn't actually need this, it'll use the token to determine the patient, not a bad thing to  have though.

2018-05-21 21:07 UTC, rnagle commented on locust/run.sh
> +set +e
Right now, `tkns` reliably fetches at least a few access tokens, but sometimes exits with code `> 0` due to a bug we haven't quite tracked down yet. I'm using `set +e` to ignore the exit code and let the script continue for the time being. We can/should tidy this up later.

2018-05-22 17:20 UTC, whytheplatypus approved these changes
lgtm

2018-05-22 17:25 UTC, merged